g01 = {}
g01_mt = {__index = g01}
function g01.new(_ARG_0_)
  return setmetatable({}, g01_mt)
end
function g01.OnInit(_ARG_0_, _ARG_1_)
  _ARG_0_.myHandle = _ARG_1_
  _ARG_0_.step = 0
  Gimmick.SetGimmickKind(_ARG_1_, GIMMICK_KIND_TREASURE_BOX_S)
  Entity.InitCollision(_ARG_1_, "g01")
  Entity.EnableBgColl(_ARG_1_, 0)
  Entity.EnableGravity(_ARG_1_, 0)
  if Item.GetTreasureBoxID(_ARG_1_) == -1 then
    print("\149\243\148\160\130h\130c\130\170\149s\144\179\n")
  elseif Item.IsOpenTreasure((Item.GetTreasureBoxID(_ARG_1_))) == false then
    Entity.EnableMarkon(_ARG_1_, 1)
    Entity.SetReplyDistSq(_ARG_1_, DISTSQ_OPEN)
    Entity.SetCommandReply(_ARG_1_, COMMAND_KIND_Open)
    Entity.SetMotion(_ARG_1_, 1)
  else
    Entity.SetMotion(_ARG_1_, 3)
  end
end
function g01.OnUpdate(_ARG_0_)
end
EntityFactory:Add("g01cd00", function(_ARG_0_)
  return (g01:new())
end)
EntityFactory:Add("g01dc00", function(_ARG_0_)
  return (g01:new())
end)
EntityFactory:Add("g01di00", function(_ARG_0_)
  return (g01:new())
end)
EntityFactory:Add("g01dp00", function(_ARG_0_)
  return (g01:new())
end)
EntityFactory:Add("g01he00", function(_ARG_0_)
  return (g01:new())
end)
EntityFactory:Add("g01jb00", function(_ARG_0_)
  return (g01:new())
end)
EntityFactory:Add("g01kg00", function(_ARG_0_)
  return (g01:new())
end)
EntityFactory:Add("g01ls00", function(_ARG_0_)
  return (g01:new())
end)
EntityFactory:Add("g01pp00", function(_ARG_0_)
  return (g01:new())
end)
EntityFactory:Add("g01rg00", function(_ARG_0_)
  return (g01:new())
end)
EntityFactory:Add("g01sb00", function(_ARG_0_)
  return (g01:new())
end)
EntityFactory:Add("g01sw00", function(_ARG_0_)
  return (g01:new())
end)
EntityFactory:Add("g01vs00", function(_ARG_0_)
  return (g01:new())
end)
EntityFactory:Add("g01yt00", function(_ARG_0_)
  return (g01:new())
end)
