g02 = {}
g02_mt = {__index = g02}
function g02.new(_ARG_0_)
  return setmetatable({}, g02_mt)
end
function g02.OnInit(_ARG_0_, _ARG_1_)
  _ARG_0_.myHandle = _ARG_1_
  _ARG_0_.step = 0
  Entity.EnableMarkon(_ARG_1_, 1)
  Entity.InitCollision(_ARG_1_, "g02")
  Entity.EnableBgColl(_ARG_1_, 0)
  Entity.EnableGravity(_ARG_1_, 0)
  Gimmick.SetGimmickKind(_ARG_1_, GIMMICK_KIND_TREASURE_BOX_B)
  if Item.GetTreasureBoxID(_ARG_1_) == -1 then
    print("\149\243\148\160\130h\130c\130\170\149s\144\179\n")
  elseif Item.IsOpenTreasure((Item.GetTreasureBoxID(_ARG_1_))) == false then
    Entity.EnableMarkon(_ARG_1_, 1)
    Entity.SetReplyDistSq(_ARG_1_, DISTSQ_OPEN)
    Entity.SetCommandReply(_ARG_1_, COMMAND_KIND_Open)
    Entity.SetMotion(_ARG_1_, 1)
  else
    Entity.SetMotion(_ARG_1_, 3)
  end
end
function g02.OnUpdate(_ARG_0_)
end
EntityFactory:Add("g02cd00", function(_ARG_0_)
  return (g02:new())
end)
EntityFactory:Add("g02dc00", function(_ARG_0_)
  return (g02:new())
end)
EntityFactory:Add("g02di00", function(_ARG_0_)
  return (g02:new())
end)
EntityFactory:Add("g02dp00", function(_ARG_0_)
  return (g02:new())
end)
EntityFactory:Add("g02he00", function(_ARG_0_)
  return (g02:new())
end)
EntityFactory:Add("g02jb00", function(_ARG_0_)
  return (g02:new())
end)
EntityFactory:Add("g02kg00", function(_ARG_0_)
  return (g02:new())
end)
EntityFactory:Add("g02ls00", function(_ARG_0_)
  return (g02:new())
end)
EntityFactory:Add("g02pp00", function(_ARG_0_)
  return (g02:new())
end)
EntityFactory:Add("g02rg00", function(_ARG_0_)
  return (g02:new())
end)
EntityFactory:Add("g02sb00", function(_ARG_0_)
  return (g02:new())
end)
EntityFactory:Add("g02sw00", function(_ARG_0_)
  return (g02:new())
end)
EntityFactory:Add("g02vs00", function(_ARG_0_)
  return (g02:new())
end)
EntityFactory:Add("g02yt00", function(_ARG_0_)
  return (g02:new())
end)
