EntityFactory:Add("g35dc00", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
EntityFactory:Add("g90dc00", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
EntityFactory:Add("g91dc00", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
EntityFactory:Add("g93dc00", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
function setBananaTrap(_ARG_0_)
  Entity.GetWorldPos(FVECTOR3.new(0, 0, 0), _ARG_0_)
  for _FORV_6_ = 1, _UPVALUE0_ do
    Bullet.CreateBullet("g54dc00", FVECTOR3.new(0, 0, 0), (FVECTOR3.new(0, 0, 0)))
  end
  _FOR_.SetEffect(_ARG_0_, "s_fb_bal_00", "FB_EXP_BAN_0", FVECTOR3.new(0, 0, 0), (FVECTOR3.new(0, 0, 0)))
end
function setGrainGrapeBall(_ARG_0_)
  Entity.GetWorldPos(FVECTOR3.new(0, 0, 0), _ARG_0_)
  for _FORV_6_ = 1, _UPVALUE0_ do
    FruitBall.CreateBall("g55dc00", FVECTOR3.new(0, 0, 0), (FVECTOR3.new(0, 0, 0)))
  end
  _FOR_.SetEffect(_ARG_0_, "s_fb_bal_00", "FB_EXP_GRP_0", FVECTOR3.new(0, 0, 0), (FVECTOR3.new(0, 0, 0)))
end
EntityFactory:Add("g49dc00", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
EntityFactory:Add("g50dc00", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
EntityFactory:Add("g51dc00", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
EntityFactory:Add("g52dc00", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
EntityFactory:Add("g53dc00", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
EntityFactory:Add("g54dc00", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
EntityFactory:Add("g55dc00", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
