WorkVec = FVECTOR3.new(0, 0, 0)
WorkVec1 = FVECTOR3.new(0, 0, 0)
EntityFactory:Add("Satellaite", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
EntityFactory:Add("FraimerainBullet", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
EntityFactory:Add("FraimeBullet", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
EntityFactory:Add("HexaCannon", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
EntityFactory:Add("HexaCannonMinSmall", function(_ARG_0_)
  return (_UPVALUE0_:new())
end)
